import type { Metadata } from "next";
import { Stack_Sans_Text } from "next/font/google";
import "./globals.css";

const stackSansText = Stack_Sans_Text({
  subsets: ["latin"],
  variable: "--font-stack-sans-text",
  weight: ["200", "300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Miuma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${stackSansText.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
